package zoo;

import herramientas.GestionFicheros;
import java.io.File;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author laura
 */
public class interCuidadores extends javax.swing.JFrame {

    /**
     * Creates new form interCuidadores
     */
    
    private static File dir = new File ("datos/datos.dat");
    private static Datos datosGeneral = null;
    private Datos dato;
    private Cuidadores cuidadoresGeneral;
    private GestionFicheros gestionar = new GestionFicheros();
    
    public interCuidadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        Nombre1 = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        Nombre2 = new javax.swing.JLabel();
        especialidad = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setMinimumSize(new java.awt.Dimension(690, 404));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.setBackground(new java.awt.Color(255, 255, 255));
        Nombre.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nombre.setText("Nombre: ");
        fondo.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 140, 60));

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Añadir cuidador");
        fondo.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 60));

        nombre.setBackground(new java.awt.Color(240, 240, 240));
        nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fondo.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 410, 60));

        Nombre1.setBackground(new java.awt.Color(255, 255, 255));
        Nombre1.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N
        Nombre1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nombre1.setText("Apellido: ");
        fondo.add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, 60));

        apellido.setBackground(new java.awt.Color(240, 240, 240));
        apellido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fondo.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 410, 60));

        Nombre2.setBackground(new java.awt.Color(255, 255, 255));
        Nombre2.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N
        Nombre2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nombre2.setText("Especialidad: ");
        fondo.add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 140, 60));

        especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fondo.add(especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 410, 50));

        jButton1.setBackground(new java.awt.Color(102, 255, 204));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        fondo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            cuidadoresGeneral=GestionFicheros.añadir(nombre.getText(), apellido.getText(), especialidad.getSelectedItem().toString());
            Datos datosGeneral= new Datos(GestionFicheros.loadDatos());
            gestionar.saveCare(datosGeneral,cuidadoresGeneral);
        } catch (IOException ex) {
            Logger.getLogger(InterCuidados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
        

    
    
    public void cargar(){
        dato = new Datos(GestionFicheros.loadDatos());
        especialidad.removeAllItems();
        int cont =0;
        String especialidadOpciones[]= new String [dato.getEspecialidades().size()];
        
        Iterator < Especialidad > it = dato.getEspecialidades().iterator(); 
        while (it.hasNext()) {
            Especialidad pac = it.next();
            especialidadOpciones[cont]=(pac.getEspecialidad());
            especialidad.addItem(pac.getEspecialidad());
            cont++;
        }
    }
    
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interCuidadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interCuidadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interCuidadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interCuidadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        if (dir.exists()){
            datosGeneral= new Datos(GestionFicheros.loadDatos());
        }
        System.out.println(datosGeneral);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                interCuidadores a = new interCuidadores();
                a.setVisible(true);
                a.cargar();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField apellido;
    private javax.swing.JComboBox<String> especialidad;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
